ifndef PCF
  PCF="../TinyFPGA-BX-pins.pcf"
endif

ifndef TARGET
  TARGET=$(notdir $(shell pwd))
endif

all: $(TARGET).bin

%.json: %.v
	yosys -p "synth_ice40 -json $@" $<

%.asc: %.json
	nextpnr-ice40 --lp8k --package cm81 --json $< --asc $@ --pcf $(PCF) -q

%.bin: %.asc
	icepack $< $@

%.verilog: %.v
	yosys -p "synth_ice40; write_verilog" $<

upload: $(TARGET).bin
	tinyprog --pyserial --program $<

clean:
	rm -f $(TARGET).bin $(TARGET).asc $(TARGET).json

